---
- name: enable php54 repo
  command: rpm -Uvh http://mirror.webtatic.com/yum/el6/latest.rpm
  ignore_errors: yes

- name: Install php-fpm and deps 
  yum: name={{ item }} state=present
  with_items:
    - php54w-fpm
    - php54w-enchant
    - php-IDNA_Convert
    - php54w-mbstring
    - php54w-mysql
    - php-PHPMailer
    - php54w-process
    - php-simplepie
    - php54w-xml
    - php54w-mcrypt
    - php54w-gd

- name: Disable default pool
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm
 
- name: Copy php-fpm configuration
  template: src=magento.conf dest=/etc/php-fpm.d/
  notify: restart php-fpm

- name: Enable php-fpm and nginx on boot
  service: name={{ item }} state=started enabled=yes
  with_items:
    - nginx
    - php-fpm 
