---
- name: install memcached
  yum: name=memcached state=present

- name: start memcached
  command: /etc/init.d/memcached start

- name: add memcached to /etc/rc.d/rc.local to start on boot
  lineinfile: dest=/etc/rc.d/rc.local line="/etc/init.d/memcached start"
