---
- name: Install Magento, MySQL, Nginx, and PHP-FPM
  hosts: all
  sudo: yes

  roles:
    - common #6
    - mysql #3 swap to percona
    - magento #7
    # - magento-sample-data #4
    - nginx #2
    - php-fpm #4
    # - memcached # production use
    - magerun
    - xdebug # development use
